export 'package:prestamo/screens/simulador.dart';
export 'package:prestamo/screens/splash.dart';
export 'package:prestamo/screens/login.dart';
export 'package:prestamo/screens/inicio.dart';
export 'package:prestamo/screens/prestamos.dart';
export 'package:prestamo/screens/detalle_prestamo.dart';
export 'package:prestamo/screens/prestamosavencer.dart';
export 'package:prestamo/screens/prestamosvencidos.dart';
export 'package:prestamo/screens/prestamofinalizado.dart';